name: markdownnotepad
description: Markdown Notepad
publish_to: "none"
version: 1.0.0+2

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    google_fonts: ^6.1.0
    flutter_native_splash: ^2.3.6
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    eval_annotation: ^0.7.0
    flutter_eval: ^0.7.1
    cached_network_image: ^3.3.0
    dart_discord_rpc:
        git:
            url: "https://gitlab.mganczarczyk.pl/TheMultii/dart_discord_rpc"
    equatable: ^2.0.5
    change_app_package_name: ^1.1.0
    package_info_plus: ^5.0.1
    auto_size_text: ^3.0.0
    flutter_feather_icons: ^2.0.0+1
    retrofit: ^4.0.3
    json_annotation: ^4.8.1
    dio: ^5.3.3
    intl: ^0.18.1
    cron: ^0.5.1
    provider: ^6.0.5
    flutter_highlight: ^0.7.0
    flutter_code_editor: ^0.3.1
    flutter_localizations:
        sdk: flutter
    highlight: ^0.7.0
    flutter_modular: ^6.3.2
    file_picker: ^6.0.0
    dynamic_height_grid_view: ^0.0.4
    url_strategy: ^0.2.0
    flutter_animate: ^4.2.0+1
    flutter_markdown: ^0.6.18
    markdown: ^7.1.1
    flutter_math_fork: ^0.7.1
    url_launcher: ^6.2.1
    color_parser: ^0.0.3
    socket_io_client: ^2.0.3+1
    lan_scanner: ^4.0.0+1
    network_info_plus: ^4.1.0
    collection: ^1.17.2
    animated_splash_screen: ^1.3.0
    http_parser: ^4.0.2
    flutter_context_menu: ^0.1.3
    file_selector: ^1.0.1
    material_symbols_icons: ^4.2711.0
    skeletonizer: ^0.8.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    hive_generator: ^2.0.1
    build_runner: ^2.4.6
    retrofit_generator: ^8.0.1
    json_serializable: ^6.7.1
    flutter_launcher_icons: ^0.13.1

flutter:
    uses-material-design: true
    assets:
        - assets/

flutter_launcher_icons:
    image_path: "assets/icon.png"
    android: true
    ios: true
    remove_alpha_ios: true
    web:
        generate: true
        image_path: "assets/icon.png"
    windows:
        generate: true
        image_path: "assets/icon.png"
    macos:
        generate: true
        image_path: "assets/icon.png"
