version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=markdownnotepad 
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    container_name: markdownnotepad-db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - '3000:3000'
    container_name: markdownnotepad-backend
volumes:
  db:
    driver: local