name: Backend CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build:
        runs-on: ubuntu-latest
        environment: build

        defaults:
            run:
                working-directory: ./markdownnotepad_backend

        strategy:
            matrix:
                node-version: [20.x, 21.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
                  cache-dependency-path: "markdownnotepad_backend/package-lock.json"
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
            - name: Upload MDN Coverage
              uses: actions/upload-artifact@v1
              with:
                  name: backend_coverage
                  path: markdownnotepad_backend/coverage
