name: Frontend CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./markdownnotepad_flutter

        steps:
            - uses: actions/checkout@v2

            - name: Setup Flutter SDK
              uses: flutter-actions/setup-flutter@v2
              with:
                  channel: stable
                  version: 3.16.3

            - name: Install dependencies
              run: flutter pub get

            - name: Analyze project source
              run: dart analyze

            - name: Run tests
              run: flutter test --coverage

            - name: Upload MDN Coverage
              uses: actions/upload-artifact@v1
              with:
                  name: frontend_coverage
                  path: coverage
